spring:
  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    host: 127.0.0.1
    port: 6379
    password: redis
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
