spring:
  data:
    mongodb:
#      host: localhost
      host: k7c109.p.ssafy.io
      port: 27017
      authentication-database: admin
      username: k7c109
      password: k7c109
      database: footprints_business
#    web:
#      pageable:
#        one-indexed-parameters: true

  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    host: 127.0.0.1
    port: 6379
    password: redis
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# freemarker
  devtools:
    restart:
      enabled: false
  freemarker:
    cache: false
  jackson:
    serialization:
      fail-on-empty-beans: false