spring:
  data:
    mongodb:
      host: localhost
#      host: j7c204.p.ssafy.io
      port: 27017
      authentication-database: admin
#      username: j7c204
#      password: seveneleven
      database: footprints_business
#    web:
#      pageable:
#        one-indexed-parameters: true

  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    host: 127.0.0.1
    port: 6379
    password: redis
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
