server:
  port: 8761
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: footprints
    enabled: true
#    key-alias: footprints
#    trust-store: classpath:keystore.p12
#    trust-store-password: footprints

spring:
#  https://github.com/piomin/sample-secure-eureka-discovery/blob/master/secure-discovery/src/main/resources/application.yml
#  참고하여 추가
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/admin/info
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
