server:
  port: 8761
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: footprints
#    enabled: true
#    key-alias: footprints
#    trust-store: classpath:keystore.p12
#    trust-store-password: footprints

spring:
  application:
    name: discovery-service

eureka:
#  instance:
#    non-secure-port-enabled: false
#    secure-port-enabled: true
    #  https://github.com/piomin/sample-secure-eureka-discovery/blob/master/secure-discovery/src/main/resources/application.yml
    #  참고하여 추가
#    securePort: ${server.port}
#    statusPageUrl: https://k7c109.p.ssafy.io:${server.port}/info
#    healthCheckUrl: https://k7c109.p.ssafy.io:${server.port}/health
#    homePageUrl: https://k7c109.p.ssafy.io:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
