spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 946667839607-isn48i7vumjc1r545qlqf5da5k7glcjk.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/auth-service/login/oauth2/code/google
            scope: profile, email
          kakao:
            client-id: 18d3f0d9580f16e2f6c8dd71471101ec
            redirect-uri: http://localhost:8080/auth-service/login/oauth2/code/kakao # http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname #, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id